//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowLong.Resources
{


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Life_Accounting.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на April.
        /// </summary>
        internal static string AprilText {
            get {
                return ResourceManager.GetString("AprilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на August.
        /// </summary>
        internal static string AugustText {
            get {
                return ResourceManager.GetString("AugustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Break.
        /// </summary>
        internal static string BreakAction {
            get {
                return ResourceManager.GetString("BreakAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End break.
        /// </summary>
        internal static string BreakEndButton {
            get {
                return ResourceManager.GetString("BreakEndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start break.
        /// </summary>
        internal static string BreakStartButton {
            get {
                return ResourceManager.GetString("BreakStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Breaks: .
        /// </summary>
        internal static string BreaksText {
            get {
                return ResourceManager.GetString("BreaksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Break: .
        /// </summary>
        internal static string BreakText {
            get {
                return ResourceManager.GetString("BreakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear history.
        /// </summary>
        internal static string ClearHistoryButton {
            get {
                return ResourceManager.GetString("ClearHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to clear history?.
        /// </summary>
        internal static string ClearHistoryText {
            get {
                return ResourceManager.GetString("ClearHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear history?.
        /// </summary>
        internal static string ClearHistoryTitle {
            get {
                return ResourceManager.GetString("ClearHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current day.
        /// </summary>
        internal static string CurrentDayButton {
            get {
                return ResourceManager.GetString("CurrentDayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current day:.
        /// </summary>
        internal static string CurrentDayText {
            get {
                return ResourceManager.GetString("CurrentDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current day.
        /// </summary>
        internal static string CurrentDayTitle {
            get {
                return ResourceManager.GetString("CurrentDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        internal static string DarkThemeButton {
            get {
                return ResourceManager.GetString("DarkThemeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Well, I&apos;ll do that.
        /// </summary>
        internal static string DayEndedAction {
            get {
                return ResourceManager.GetString("DayEndedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have worked hard, now you can relax, for example, watching a movie, reading an interesting book or playing sports😉.
        /// </summary>
        internal static string DayEndedText {
            get {
                return ResourceManager.GetString("DayEndedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day is over!.
        /// </summary>
        internal static string DayEndedTitle {
            get {
                return ResourceManager.GetString("DayEndedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Congratulations, you have successfully fulfilled the working norm of the current day👏.
        /// </summary>
        internal static string DayIsOverText {
            get {
                return ResourceManager.GetString("DayIsOverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working day is over!.
        /// </summary>
        internal static string DayIsOverTitle {
            get {
                return ResourceManager.GetString("DayIsOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day successfully deleted.
        /// </summary>
        internal static string DaySuccessDeleteText {
            get {
                return ResourceManager.GetString("DaySuccessDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day successfully completed.
        /// </summary>
        internal static string DaySuccessEndedText {
            get {
                return ResourceManager.GetString("DaySuccessEndedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day successfully updated.
        /// </summary>
        internal static string DaySuccessUpdatedText {
            get {
                return ResourceManager.GetString("DaySuccessUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на December.
        /// </summary>
        internal static string DecemberText {
            get {
                return ResourceManager.GetString("DecemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to remove this break?.
        /// </summary>
        internal static string DeleteBreakText {
            get {
                return ResourceManager.GetString("DeleteBreakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove the break?.
        /// </summary>
        internal static string DeleteBreakTitle {
            get {
                return ResourceManager.GetString("DeleteBreakTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete the account day?.
        /// </summary>
        internal static string DeleteDayText {
            get {
                return ResourceManager.GetString("DeleteDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete day?.
        /// </summary>
        internal static string DeleteDayTitle {
            get {
                return ResourceManager.GetString("DeleteDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string EditAction {
            get {
                return ResourceManager.GetString("EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing.
        /// </summary>
        internal static string EditingTitle {
            get {
                return ResourceManager.GetString("EditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History is empty.
        /// </summary>
        internal static string EmptyHistoryText {
            get {
                return ResourceManager.GetString("EmptyHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End the day.
        /// </summary>
        internal static string EndDayButton {
            get {
                return ResourceManager.GetString("EndDayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to complete the current day?.
        /// </summary>
        internal static string EndDayText {
            get {
                return ResourceManager.GetString("EndDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End the day?.
        /// </summary>
        internal static string EndDayTitle {
            get {
                return ResourceManager.GetString("EndDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на February.
        /// </summary>
        internal static string FebruaryText {
            get {
                return ResourceManager.GetString("FebruaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fri.
        /// </summary>
        internal static string FridayShortText {
            get {
                return ResourceManager.GetString("FridayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Friday.
        /// </summary>
        internal static string FridayText {
            get {
                return ResourceManager.GetString("FridayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have crossed the equator of the working day. There&apos;s only half of it left💪.
        /// </summary>
        internal static string HalfWorkText {
            get {
                return ResourceManager.GetString("HalfWorkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Half done!.
        /// </summary>
        internal static string HalfWorkTitle {
            get {
                return ResourceManager.GetString("HalfWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History .
        /// </summary>
        internal static string HistoryButton {
            get {
                return ResourceManager.GetString("HistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History successfully cleared.
        /// </summary>
        internal static string HistorySuccessClearText {
            get {
                return ResourceManager.GetString("HistorySuccessClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History.
        /// </summary>
        internal static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на January.
        /// </summary>
        internal static string JanuaryText {
            get {
                return ResourceManager.GetString("JanuaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на July.
        /// </summary>
        internal static string JulyText {
            get {
                return ResourceManager.GetString("JulyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на June.
        /// </summary>
        internal static string JuneText {
            get {
                return ResourceManager.GetString("JuneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string LightThemeButton {
            get {
                return ResourceManager.GetString("LightThemeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounting of working hours.
        /// </summary>
        internal static string MainHeaderText {
            get {
                return ResourceManager.GetString("MainHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на March.
        /// </summary>
        internal static string MarchText {
            get {
                return ResourceManager.GetString("MarchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на May.
        /// </summary>
        internal static string MayText {
            get {
                return ResourceManager.GetString("MayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message to support.
        /// </summary>
        internal static string MessageToSupport {
            get {
                return ResourceManager.GetString("MessageToSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mon.
        /// </summary>
        internal static string MondayShortText {
            get {
                return ResourceManager.GetString("MondayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monday.
        /// </summary>
        internal static string MondayText {
            get {
                return ResourceManager.GetString("MondayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Well, I&apos;ll do that.
        /// </summary>
        internal static string NotWorkingDayAction {
            get {
                return ResourceManager.GetString("NotWorkingDayAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alas, today is a day off, so add to the account a new working day will not work. If you need to add a new working day, go to the &quot;Working days&quot; section of the settings and activate the desired day.
        /// </summary>
        internal static string NotWorkingDayText {
            get {
                return ResourceManager.GetString("NotWorkingDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day off!.
        /// </summary>
        internal static string NotWorkingDayTitle {
            get {
                return ResourceManager.GetString("NotWorkingDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на November.
        /// </summary>
        internal static string NovemberText {
            get {
                return ResourceManager.GetString("NovemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на October.
        /// </summary>
        internal static string OctoberText {
            get {
                return ResourceManager.GetString("OctoberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overwork:.
        /// </summary>
        internal static string OverworkText {
            get {
                return ResourceManager.GetString("OverworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remain only:.
        /// </summary>
        internal static string RemainedAll {
            get {
                return ResourceManager.GetString("RemainedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is the time left to work out taking into account the working rate of the current day, as well as taking into account all the overwork and shortcomings, information about which is stored in the history of the application.
        /// </summary>
        internal static string RemainedAllText {
            get {
                return ResourceManager.GetString("RemainedAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remain only.
        /// </summary>
        internal static string RemainedAllTitle {
            get {
                return ResourceManager.GetString("RemainedAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remained current:.
        /// </summary>
        internal static string RemainedCurrent {
            get {
                return ResourceManager.GetString("RemainedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is the time that is left to work out taking into account the working rate of the current day.
        /// </summary>
        internal static string RemainedCurrentText {
            get {
                return ResourceManager.GetString("RemainedCurrentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remained current.
        /// </summary>
        internal static string RemainedCurrentTitle {
            get {
                return ResourceManager.GetString("RemainedCurrentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sat.
        /// </summary>
        internal static string SaturdayShortText {
            get {
                return ResourceManager.GetString("SaturdayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saturday.
        /// </summary>
        internal static string SaturdayText {
            get {
                return ResourceManager.GetString("SaturdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string SaveDayButton {
            get {
                return ResourceManager.GetString("SaveDayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the action.
        /// </summary>
        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected day:.
        /// </summary>
        internal static string SelectedDayText {
            get {
                return ResourceManager.GetString("SelectedDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на September.
        /// </summary>
        internal static string SeptemberText {
            get {
                return ResourceManager.GetString("SeptemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sun.
        /// </summary>
        internal static string SundayShortText {
            get {
                return ResourceManager.GetString("SundayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sunday.
        /// </summary>
        internal static string SundayText {
            get {
                return ResourceManager.GetString("SundayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support .
        /// </summary>
        internal static string SupportButton {
            get {
                return ResourceManager.GetString("SupportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        internal static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thurs.
        /// </summary>
        internal static string ThursdayShortText {
            get {
                return ResourceManager.GetString("ThursdayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thursday.
        /// </summary>
        internal static string ThursdayText {
            get {
                return ResourceManager.GetString("ThursdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time accounting.
        /// </summary>
        internal static string TimeAccounting {
            get {
                return ResourceManager.GetString("TimeAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The time selection elements set the working time rate, i.e. the number of working hours.
        /// </summary>
        internal static string TimePickerText {
            get {
                return ResourceManager.GetString("TimePickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tues.
        /// </summary>
        internal static string TuesdayShortText {
            get {
                return ResourceManager.GetString("TuesdayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tuesday.
        /// </summary>
        internal static string TuesdayText {
            get {
                return ResourceManager.GetString("TuesdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weaknesses:.
        /// </summary>
        internal static string WeaknessesText {
            get {
                return ResourceManager.GetString("WeaknessesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wed.
        /// </summary>
        internal static string WednesdayShortText {
            get {
                return ResourceManager.GetString("WednesdayShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wednesday.
        /// </summary>
        internal static string WednesdayText {
            get {
                return ResourceManager.GetString("WednesdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekdays.
        /// </summary>
        internal static string WeekdaysButton {
            get {
                return ResourceManager.GetString("WeekdaysButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekdays.
        /// </summary>
        internal static string WeekdaysText {
            get {
                return ResourceManager.GetString("WeekdaysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekday.
        /// </summary>
        internal static string WeekdayText {
            get {
                return ResourceManager.GetString("WeekdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to go to work on the weekend? The time worked today will be reflected in the quality of processing.
        /// </summary>
        internal static string WeekendAlertText {
            get {
                return ResourceManager.GetString("WeekendAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day off!.
        /// </summary>
        internal static string WeekendAlertTitle {
            get {
                return ResourceManager.GetString("WeekendAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekend.
        /// </summary>
        internal static string WeekendText {
            get {
                return ResourceManager.GetString("WeekendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrived at work.
        /// </summary>
        internal static string WorkArrivedButton {
            get {
                return ResourceManager.GetString("WorkArrivedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave work.
        /// </summary>
        internal static string WorkLeaveButton {
            get {
                return ResourceManager.GetString("WorkLeaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work: .
        /// </summary>
        internal static string WorkText {
            get {
                return ResourceManager.GetString("WorkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, clear.
        /// </summary>
        internal static string YesClearHistoryText {
            get {
                return ResourceManager.GetString("YesClearHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thanks.
        /// </summary>
        internal static string YesDayIsOverText {
            get {
                return ResourceManager.GetString("YesDayIsOverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, remove.
        /// </summary>
        internal static string YesDeleteBreakText {
            get {
                return ResourceManager.GetString("YesDeleteBreakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, delete.
        /// </summary>
        internal static string YesDeleteDayText {
            get {
                return ResourceManager.GetString("YesDeleteDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, complete.
        /// </summary>
        internal static string YesEndDayText {
            get {
                return ResourceManager.GetString("YesEndDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Great.
        /// </summary>
        internal static string YesHalfWorkText {
            get {
                return ResourceManager.GetString("YesHalfWorkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, go to work.
        /// </summary>
        internal static string YesWeekendAlertText {
            get {
                return ResourceManager.GetString("YesWeekendAlertText", resourceCulture);
            }
        }
    }
}
